app/config/urls.py
from django.contrib import admin, sitemaps
from django.urls import path, reverse
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from tealist import views
from tealist.sitemaps import *


class StaticViewSitemap(sitemaps.Sitemap):
    priority = 0.9
    changefreq = "weekly"

    def items(self):
        return ["index", "vendors", "vendors_submit", "collections", "teas-table"]

    def location(self, item):
        return reverse(item)


sitemaps = {
    "static": StaticViewSitemap,
    "vendors": VendorSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("vendors/list", views.VendorListView, name="vendors"),
    path("vendors/table", views.VendorTableView.as_view(), name="vendors-table"),
    path("vendors/submit/", views.VendorSubmitView, name="vendors_submit"),
    path("vendors/<str:slug>/", views.VendorDetailView, name="vendor-detail"),
    path("vendors/<str:slug>/rate", views.VendorRating, name="vendor-rate"),
    path("teas/table", views.TeaTableView.as_view(), name="teas-table"),
    path("collections/list/", views.CollectionListView, name="collections"),
    path("collections/new/", views.CollectionNewView, name="collections_new"),
    path(
        "collections/new/preview/",
        views.CollectionPreviewView,
        name="collections_new_preview",
    ),
    path(
        "collections/<str:slug>/", views.CollectionDetailView, name="collection-detail"
    ),
    path("collections/<str:slug>/rate", views.CollectionRating, name="collection-rate"),
    path("releases/", views.ReleaseHistory, name="releases"),
    path("privacy/", views.PrivacyPolicy, name="privacy"),
    path("terms/", views.TermsAndConditions, name="terms"),
    path("error/", views.returnError, name="error"),
    path("helloWorld/", views.helloWorld, name="helloWorld"),
    path("accounts/", include("allauth.urls")),  # Used by django-allauth
    path(
        r"comments/", include("django_comments_xtd.urls")
    ),  # Used by django-comments-xtd
    path("accounts/profile/", views.ProfileView, name="profile"),
    path("accounts/profile/update", views.ProfileUpdate, name="profile_update"),
    path("__debug__/", include("debug_toolbar.urls")),  # Used by Django debug toolbar
    path(
        "__reload__/", include("django_browser_reload.urls")
    ),  # Used by django-tailwind[reload]
    path(
        "cookie_consent_check/", views.CookieConsentCheck, name="cookie_consent_check"
    ),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

# Only add this when we are in debug mode.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/tealist/models.py
from django.db import models
from djmoney.models.fields import MoneyField
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
import uuid, json
from django.db.models import Count
from meta.models import ModelMeta


def GenerateGuid():
    return str(uuid.uuid4())[:4]


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE
    )  # Delete profile when user is deleted
    image = models.ImageField(default="default.jpg", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} Profile"  # show how we want it to be displayed


class Location(models.Model):
    name = models.CharField(max_length=30, help_text="Country/region name", unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Locations"


class Variety(models.Model):
    name = models.CharField(
        max_length=30, help_text="Type of tea or offering", unique=True
    )
    alias = ArrayField(
        models.CharField(max_length=10, blank=True), size=8, blank=True, default=list
    )
    description = models.TextField(
        help_text="Description of this type of tea", blank=True
    )

    def __str__(self):
        return self.name


class Vendor(ModelMeta, models.Model):
    name = models.CharField(
        max_length=30, help_text="Business name of the vendor", unique=True
    )
    url = models.URLField(help_text="URL for this vendor's store", unique=True)
    url_alt = models.URLField(
        help_text="Alternate URL for this vendor's store.", blank=True
    )
    description = models.TextField(help_text="Description of the vendor", blank=True)
    store_location = models.ManyToManyField(
        Location,
        help_text="Select locations this vendor ships from",
        blank=True,
        related_name="store_location",
    )
    ship_to = models.ManyToManyField(
        Location,
        help_text="Select locations this vendor ships to",
        blank=True,
        related_name="ship_to",
    )
    tea_source = models.ManyToManyField(
        Location,
        help_text="Select locations this vendor sources tea from",
        blank=True,
        related_name="tea_source",
    )
    featured = models.BooleanField(default=False)
    variety = models.ManyToManyField(
        Variety, help_text="Select the varieties of tea this vendor sells", blank=True
    )
    established = models.DateField(blank=True, null=True)
    created = models.DateField(auto_now_add=True)
    slug = models.SlugField(max_length=250, blank=True)
    rating = models.DecimalField(max_digits=2, decimal_places=1, null=True, default=0.0)
    active = models.BooleanField(default=False)

    _metadata = {
        "title": "meta_title",
        "description": "Looking for a new tea vendor? Search our list of vendors to find the perfect tea offerings for your next cup.",
    }

    def meta_title(self):
        if self.name:
            return f"Tea Hookup | {self.name}"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/vendors/%s/" % self.slug

    def save(self, *args, **kwargs):
        value = self.name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


class comment(models.Model):
    RATING_CHOICES = (
        (5, "5"),
        (4, "4"),
        (3, "3"),
        (2, "2"),
        (1, "1"),
    )

    vendor = models.ForeignKey(
        Vendor, on_delete=models.CASCADE, related_name="comments"
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    value = models.IntegerField(choices=RATING_CHOICES)

    def save(self, *args, **kwargs):
        v = self.vendor
        Comments = comment.objects.filter(vendor=v)
        avg = float(0)
        for c in Comments:
            avg += float(c.value)

        avg += float(self.value)
        avg = avg / (len(Comments) + 1)
        Vendor.rating = avg
        Vendor.save()
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["created_on"]
        constraints = [
            models.UniqueConstraint(
                fields=["vendor", "user"], name="One comment per user per vendor"
            )
        ]


class Collection(models.Model):
    unique_id = models.CharField(max_length=6, default=GenerateGuid(), editable=False)
    name = models.CharField(
        max_length=40, help_text="What do you want to call this vendor"
    )
    vendors = models.ManyToManyField(
        Vendor,
        help_text="Which vendors belong to this collection",
        related_name="collection_vendors",
    )
    private = models.BooleanField(default=True)
    content = models.TextField(help_text="Info about this collection", blank=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="collection_owner"
    )
    active = models.BooleanField(default=True)
    rating = models.ManyToManyField(User, related_name="collection_voters", blank=True)
    slug = models.SlugField(max_length=250, blank=True, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/collections/%s/" % self.slug

    def get_location_stats(self):
        location_count = (
            Location.objects.prefetch_related("Vendor")
            .filter(tea_source__in=self.vendors.all())
            .annotate(location_count=Count("tea_source"))
        )

        return json.dumps(list(location_count.values("name", "location_count")))

    def save(self, *args, **kwargs):
        value = f"{self.name}-{self.unique_id}"
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


class Rating(models.Model):
    RATING_CHOICES = (
        (5, "5"),
        (4.5, "4.5"),
        (4, "4"),
        (3.5, "3.5"),
        (3, "3"),
        (2.5, "2.5"),
        (2, "2"),
        (1.5, "1.5"),
        (1, "1"),
        (0.5, "0.5"),
    )

    vendor = models.ForeignKey(
        Vendor, on_delete=models.CASCADE, related_name="vendor_rating"
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    value = models.DecimalField(
        max_digits=2, decimal_places=1, null=True, choices=RATING_CHOICES
    )

    class Meta:
        verbose_name_plural = "Ratings"
        unique_together = ("vendor", "user")

    def __str__(self):
        return f"{self.vendor} - {self.user} | {self.value}"


class Tea(models.Model):
    vendor = models.ForeignKey(
        Vendor, on_delete=models.CASCADE, related_name="tea_vendor"
    )
    title = models.CharField(max_length=256)
    published_at = models.DateField(blank=True, null=True)
    created_at = models.DateField(blank=True, null=True)
    updated_at = models.DateField(blank=True, null=True)
    handle = models.CharField(max_length=256)
    variety = models.ManyToManyField(Variety, blank=True, default="")
    on_sale = models.BooleanField(default=False)

    class Meta:
        unique_together = ("vendor", "handle")

    def __str__(self):
        return f"{self.vendor} | {self.title}"


class TeaVariant(models.Model):
    tea = models.ForeignKey(
        Tea, on_delete=models.CASCADE, related_name="tea_variant", verbose_name="Price"
    )
    title = models.CharField(max_length=256)
    price = MoneyField(
        max_digits=14, decimal_places=2, null=True, default_currency=None
    )
    compare_at_price = MoneyField(
        max_digits=14, decimal_places=2, null=True, default_currency=None
    )

    class Meta:
        unique_together = ("tea", "title")

    def __str__(self):
        return f"{self.tea} | {self.title}"

app/tealist/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import *


class VendorForm(forms.ModelForm):
    name = forms.CharField(
        help_text="The business name of the vendor",
        widget=forms.TextInput(
            attrs={
                "class": "input",
            }
        ),
    )
    url = forms.CharField(
        help_text="The URL of the vendor",
        widget=forms.URLInput(
            attrs={
                "class": "input",
            }
        ),
    )
    url_alt = forms.CharField(
        help_text="An alternate URL, if one exists. Such as for a global site",
        label="Alternative URL",
        required=False,
        widget=forms.URLInput(
            attrs={
                "class": "input",
                "placeholder": "Optional",
            }
        ),
    )
    description = forms.CharField(
        help_text="Description of the vendor. Often pulled from about pages or Google summaries",
        widget=forms.Textarea(
            attrs={
                "class": "textarea",
                "rows": 4,
                "cols": 50,
            }
        ),
    )
    ship_to = forms.ModelMultipleChoiceField(
        label="Ships to",
        help_text="Where does this vendor ship to?",
        queryset=Location.objects.all().exclude(ship_to__isnull=True),
        widget=forms.CheckboxSelectMultiple(attrs={"class": "peer hidden"}),
    )
    store_location = forms.ModelMultipleChoiceField(
        queryset=Location.objects.all().exclude(store_location__isnull=True),
        help_text="Where does this vendor ship from?",
        widget=forms.CheckboxSelectMultiple(attrs={"class": "peer hidden"}),
    )
    tea_source = forms.ModelMultipleChoiceField(
        help_text="Where does this vendor source its tea from?",
        queryset=Location.objects.all().exclude(tea_source__isnull=True),
        widget=forms.CheckboxSelectMultiple(attrs={"class": "peer hidden"}),
    )
    variety = forms.ModelMultipleChoiceField(
        help_text="What sort of teas does this vendor sell?",
        queryset=Variety.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={"class": "peer hidden"}),
    )

    class Meta:
        model = Vendor
        fields = [
            "name",
            "description",
            "store_location",
            "ship_to",
            "tea_source",
            "url",
            "url_alt",
            "variety",
        ]


class CollectionForm(forms.ModelForm):
    name = forms.CharField(
        help_text="What do you want to call this collection?",
        widget=forms.TextInput(
            attrs={
                "class": "input w-full",
            }
        ),
    )
    vendors = forms.ModelMultipleChoiceField(
        help_text="Choose the vendors to add to this collection - up to 10.",
        queryset=Vendor.objects.all().exclude(active=False),
        widget=forms.SelectMultiple(
            attrs={
                "id": "input-vendors",
                "placeholder": "Please pick at least three vendors.",
                "autocomplete": "off",
            }
        ),
    )
    content = forms.CharField(
        label="",
        widget=forms.Textarea(
            attrs={
                "id": "SimpleMDE",
                "class": "textarea",
                "placeholder": "Some additional context for this collection, if necessary.",
                "rows": 4,
                "cols": 50,
            }
        ),
    )

    class Meta:
        model = Collection
        fields = ["name", "vendors", "content"]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image"]


class RatingForm(forms.ModelForm):
    CHOICES = Rating.RATING_CHOICES

    value = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=CHOICES,
    )

    class Meta:
        model = Rating
        fields = ["value"]

app/theme/templates/comments/delete.html
{% extends "django_comments_xtd/base.html" %}
{% load i18n %}
{% load comments_xtd %}

{% block title %}{% trans "Remove comment" %}{% endblock %}

{% block content %}
<div class="mb-4">
  <h3 class="text-center">{% trans "Remove this comment?" %}</h3>
  <hr/>
</div>
<p class="lead text-center">{% trans "As a moderator you can delete comments. Deleting a comment does not remove it from the site, only prevents your website from showing the text. Click on the remove button to delete the following comment:" %}</p>
<div class="row">
  <div class="offset-md-1 col-md-10">
    <div class="card mb-4">
      <div class="card-body">
        <div class="media">
          <div class="mr-3">
            {{ comment.user_email|xtd_comment_gravatar }}
          </div>
          <div class="media-body">
            <h6 class="mb-1 small">
              {{ comment.submit_date|date:"N j, Y, P" }}&nbsp;-&nbsp;
              {% if comment.user_url %}
              <a href="{{ comment.user_url }}" target="_new">
                {{ comment.user_name }}
              </a>
              {% else %}
              {{ comment.user_name }}
              {% endif %}
            </h6>
            <p>{{ comment.comment }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="offset-md-1 col-md-10">
    <form action="." method="post">{% csrf_token %}
      <input type="hidden" name="next" value="{{ comment.get_absolute_url }}"/>
        <div class="form-group">
          <div class="text-center">
            <input type="submit" name="submit" class="btn btn-danger" value="{% trans "Remove" %}"/>
            <a class="btn btn-secondary" href="{{ comment.get_absolute_url }}">{% trans 'cancel' %}</a>
          </div>
        </div>
    </form>
  </div>
</div>
{% endblock %}

app/theme/templates/comments/deleted.html
{% extends "django_comments_xtd/base.html" %}
{% load i18n %}
{% load comments_xtd %}

{% block title %}{% trans "Comment removed" %}.{% endblock %}

{% block header %}
<a href="{{ comment.content_object.get_absolute_url }}">{{ comment.content_object }}</a>
{% endblock %}

{% block content %}
<h4 class="text-center">{% trans "The comment has been removed." %}</h4>
<p class="text-center">{% trans "Thank you for taking the time to improve the quality of discussion in our site." %}<p>
{% endblock %}

app/theme/templates/comments/flag.html
{% load i18n %}
{% load comments_xtd %}

{% block content %}
<form method="dialog">
  <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
</form>
<div class="mb-4">
  <h3 class="font-serif font-bold text-center">{% trans "Flag this comment?" %}</h3>
  <p class="text-accent text-center">{% trans "Click on the flag button to mark the following comment as inappropriate." %}</p>
  <hr/>
</div>


<div class="media join content-start gap-4">
  {% if comment.user.profile.image.url %}
  <img class="mask mask-squircle" src="{{ comment.user.profile.image.url }}" width="64"/>
  {% else %}
  <img src="{{ comment.user_email|xtd_comment_gravatar_url }}" class="mask mask-squircle" width="64"/>
  {% endif %}
  <div class="media-body">
    <h6 class="text-accent text-sm flex flex-row justify-between items-center w-full">
      {{ comment.submit_date|date:"N j, Y, P" }}&nbsp;-&nbsp;
      {% if comment.user_url %}
      <a href="{{ comment.user_url }}" target="_new">{% endif %}
        {{ comment.user_name }}
        {% if comment.user_url %}
      </a>{% endif %}
    </h6>
    <p>{{ comment.comment }}</p>
  </div>
</div>

    {% with object_absolute_url=comment.content_object.get_absolute_url %}
    {% if object_absolute_url %}
    <p class="text-center">
      {% trans "Posted to "%}&nbsp;<a href="{{ object_absolute_url }}">{{ comment.content_object }}</a>
    </p>
    {% endif %}
    {% endwith %}
    <div class="visible-md-block">
      <hr/>
    </div>


    <form action="." method="post">{% csrf_token %}
      <input type="hidden" name="next" value="{{ comment.get_absolute_url }}"/>
      <div class="form-control">
        <div class="text-center">
          <input type="submit" name="submit" class="btn btn-secondary hover:btn-error w-full font-serif" value="{% trans "Flag" %}"/>
        </div>
      </div>
    </form>

{% endblock %}

app/theme/templates/comments/flagged.html
{% extends "django_comments_xtd/base.html" %}
{% load i18n %}
{% load comments_xtd %}

{% block title %}{% trans "Comment flagged" %}.{% endblock %}

{% block header %}
<a href="{{ comment.content_object.get_absolute_url }}">{{ comment.content_object }}</a>
{% endblock %}

{% block content %}
<h4 class="text-center">{% trans "The comment has been flagged." %}</h4>
<p class="text-center">{% trans "Thank you for taking the time to improve the quality of discussion in our site." %}<p>
{% endblock %}

app/theme/templates/comments/form.html
{% load i18n %}
{% load comments %}

<form method="POST" action="{% comment_form_target %}" onsubmit="post.disabled = true; return true;">
    {% csrf_token %}
    <fieldset class="flex flex-col">
        <input type="hidden" name="next" value="{% url 'comments-xtd-sent' %}" />

        <div class="alert alert-danger hidden" data-comment-element="errors">
        </div>

        {% for field in form %}
        {% if field.is_hidden %}<div>{{ field }}</div>{% endif %}
        {% endfor %}

        <div style="display:none">{{ form.honeypot }}</div>

        <div class="form-control mb-2 {% if 'comment' in form.errors %}has-danger{% endif %}">
            <textarea name="{{ form.comment.html_name }}" id="{{ form.comment.id_for_label }}" placeholder="Please share your thoughts..." class="textarea w-full" required=""></textarea>
        </div>

        {% if not request.user.is_authenticated or not request.user.email %}
        <div class="form-control {% if 'email' in form.errors %}has-danger{% endif %}">
            <label for="id_email" class="col-form-label col-md-3 text-right">
            </label>
            <div class="col-md-12">
                {{ form.email }}
                <span class="form-text small">{{ form.email.help_text }}</span>
            </div>
        </div>
        {% endif %}

        {% if not request.user.is_authenticated %}
        <div class="form-control {% if 'url' in form.errors %}has-error{% endif %}">
            <label for="id_url" class="col-form-label col-md-3 text-right">
                {{ form.url.label }}
            </label>
            <div class="col-md-12">
                {{ form.url }}
            </div>
        </div>
        {% endif %}


        <div class="form-control">
            <label for="id_followup{% if cid %}_{{ cid }}{% endif %}">
                <input type="checkbox" name="{{ form.followup.html_name }}" id="{{ form.followup.id_for_label }}" class="toggle toggle-success">
                <span class="label-text">&nbsp;{{ form.followup.label }}</span>
            </label>
        </div>

    </fieldset>

    <div class="join w-full my-3 gap-2">
        <input type="submit" name="post" value="{% trans 'Post comment' %}" class="btn btn-primary font-serif w-full" />
        <!-- <input type="submit" name="preview" value="{% trans 'preview' %}" class="btn btn-primary" /> -->
    </div>
</form>

app/theme/templates/comments/list.html
{% load i18n %}
{% load comments %}
{% load comments_xtd %}

<div id="comments" class="media-list">
  {% for comment in comment_list %}
  <div class="media pb-2">
    <a name="c{{ comment.id }}"></a>
    <span class="mr-3">{{ comment.user_email|xtd_comment_gravatar }}</span>
    <div class="media-body">
      <div class="comment pb-3">
        <h6 class="mb-1 small d-flex">
          <div class="mr-auto">{{ comment.submit_date }}&nbsp;-&nbsp;{% if comment.url and not comment.is_removed %}<a href="{{ comment.url }}" target="_new">{% endif %}{{ comment.name }}{% if comment.url %}</a>{% endif %}&nbsp;&nbsp;<a class="permalink" title="comment permalink" href="{% get_comment_permalink comment %}">¶</a></div>
        </h6>
        <div class="content">
          {% if comment.is_removed %}
          <p class="text-muted">{% trans "This comment has been removed." %}</p>
          {% else %}
          <div class="content">
            {% include "includes/django_comments_xtd/comment_content.html" with content=comment.comment %}
          </div>
          {% endif %}
          {% if comment.allow_thread and not comment.is_removed %}
          <a class="small mutedlink" href="{{ comment.get_reply_url }}">
            {% trans "Reply" %}
          </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

app/theme/templates/comments/posted.html
{% extends "django_comments_xtd/base.html" %}
{% load i18n %}

{% block content %}
<div class="mb-4">
    <h3 class="text-center">{% trans "Comment confirmation requested." %}</h3>
    <hr/>
</div>
<div class="row justify-content-center flex-fill">
    <div class="col-md-7">
        <p class="lead text-center">
            {% blocktrans %}A confirmation message has been sent to your
            email address. Please, click on the link in the message to confirm
            your comment.{% endblocktrans %}
        </p>
        <p class="pt-5 text-center">
            {% trans 'Go back to' %}: <a href="{{ target.get_absolute_url }}">{{ target }}</a>
        </p>
    </div>
</div>
{% endblock %}

app/theme/templates/comments/preview.html
{% extends "django_comments_xtd/base.html" %}
{% load i18n %}
{% load comments_xtd %}

{% block title %}{% trans "Preview your comment" %}{% endblock %}

{% block content %}
<div class="container mx-auto card bg-base-300 shadow-xl">
  <div class="mb-4">
    <h3 class="text-center">{% trans "Preview your comment" %}</h3>
    <hr/>
  </div>
  <p class="lead text-center">
    {% trans "Preview of your comment for:" %}<br/>
    <a href="{{ form.target_object.get_absolute_url }}">{{ form.target_object }}</a>
  </p>
  <div class="row">
    <div class="col-md-12">
      <hr/>
      {% if not comment %}
      <em>{% trans "Empty comment." %}</em>
      {% else %}
      <div class="media">
        <div class="mr-3">
          {{ form.cleaned_data.email|xtd_comment_gravatar }}
        </div>
        <div class="media-body">
          <div class="comment pb-3">
            <h6 class="mb-1 small d-flex">
              <div class="mr-auto">
                {% now "N j, Y, P" %}&nbsp;-&nbsp;
                {% if form.cleaned_data.url %}
                <a href="{{ form.cleaned_data.url }}" target="_new">
                  {{ form.cleaned_data.name }}
                </a>
                {% else %}
                  {{ form.cleaned_data.name }}
                {% endif %}
              </div>
            </h6>
            <div class="content">{{ comment }}</div>
          </div>
        </div>
      </div>
      {% endif %}
      <div class="card mt-4 mb-5">
        <div class="card-body">
          <h4 class="card-title text-center pb-3">{% trans "Post your comment" %}</h4>
          {% include "comments/form.html" %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}